run_type: ts

params:
  L_w: 60
  L_d: 120
  staff_velocity: 0.58
  drone_velocity: 0.83
  num_staff: 1
  num_drone: 1

data_path: data/old/12.20.4.txt

result_folder: result

tabu_params:
  tabu_size: 5
  max_iter: 100
  alpha1: 1
  alpha2: 1
  beta: 0.5

solver:
  solver: GUROBI
  solver_log: false
  num_worker: -1
  time_limit: 1800
  model_params:
    gurobi: { }
    cplex: { }

test:
  data_path: data/old/12.20.4.txt
  staff: [ [ 5 ],[ 2 ],[ 10 ] ]
  drone: [ [ [ 11,7 ] ],[ [ 8,6,12,3 ] ],[ [ 9,1,4 ] ] ]