run_type: cal
#run_type: result
#run_type: new_tabu
#run_type: lcs
run_type: tabu
#run_type: test

params:
  L_w: 60
  L_d: 120
  staff_velocity: 0.58
  drone_velocity: 0.83
  num_staff: 2 # tinh tong khoang cach tu depot toi tung khach hang, roi chia cho van toc, chia tiep cho thoi gian cho
  num_drone: 2 # toi da chi su dung 3 drone
  use_ejection: True
  use_inter: True
  use_intra: True

data_path: [data/old/10.5.1.txt]
except_path: []

result_folder: result

local_search_params:
  max_iter: 500
  max_stable: 10 #20
  num_runs: 1

tabu_params:
  tabu_size: 5
  max_iter: 500
  num_runs: 10
  terminate_iter: 200
  alpha1: 1
  alpha2: 1
  beta: 0.5
  epsilon: 1e-3
  use_weights: True
  action_order: ["move10", "move11", "move21", "move20", "move2opt"]
  action_weights: { "move10": 0.2, "move11": 0.2,
                    "move20": 0.2, "move21": 0.2,
                    "move2opt": 0.2}

ejection:
  max_level: 2

solver:
  solver: GUROBI
  solver_log: false
  num_worker: -1
  time_limit: 1800
  model_params:
    gurobi: { }
    cplex: { }

test:
  data_path: data/old/20.5.1.txt
  staff: [[20,6,8],[11,10,9],[14,17]]
  drone: []


result:
  type: tabu
  path: result_tabu/***/**/*.json
  result: result_tabu