params:
    L_w: 30
    L_d: 60
    staff_velocity: 0.58
    drone_velocity: 0.83
    num_staff: 2
    num_drone: 2

data_path: data/old/10.10.1.txt

result_folder: result

solver:
    solver: GUROBI
    solver_log: false
    num_worker: -1
    time_limit: 180
    model_params:
        gurobi: {}
